/**
 * Items.js — item + weapon definitions and the loot tables that spawn them.
 * Scarcity is tuned here: most containers give nothing, and the good stuff
 * lives in places that are annoying (or dangerous) to reach.
 */

export const ItemType = {
  CONSUMABLE: 'consumable',
  WEAPON: 'weapon',
  TOOL: 'tool',
  RESOURCE: 'resource',
  AMMO: 'ammo',
};

export const ITEMS = {
  water_bottle: {
    id: 'water_bottle',
    name: 'Water Bottle',
    short: 'Water',
    type: ItemType.CONSUMABLE,
    icon: '💧',
    stack: 6,
    weight: 0.6,
    supply: 1,
    desc: 'Half a litre, still sealed. Tastes like plastic. Tastes like living.',
    effects: { thirst: 42 },
    useVerb: 'Drink',
  },
  soda: {
    id: 'soda',
    name: 'Warm Soda',
    short: 'Soda',
    type: ItemType.CONSUMABLE,
    icon: '🥤',
    stack: 6,
    weight: 0.5,
    supply: 1,
    desc: 'Flat and warm. Sugar is sugar.',
    effects: { thirst: 26, hunger: 8, stamina: 15 },
    useVerb: 'Drink',
  },
  canned_food: {
    id: 'canned_food',
    name: 'Canned Beans',
    short: 'Beans',
    type: ItemType.CONSUMABLE,
    icon: '🥫',
    stack: 6,
    weight: 0.9,
    supply: 1,
    desc: 'Dented. Two years past the date. Nobody is checking dates any more.',
    effects: { hunger: 46 },
    useVerb: 'Eat',
  },
  energy_bar: {
    id: 'energy_bar',
    name: 'Cereal Bar',
    short: 'Bar',
    type: ItemType.CONSUMABLE,
    icon: '🍫',
    stack: 8,
    weight: 0.2,
    supply: 1,
    desc: 'Crushed flat in someone’s glovebox. Still food.',
    effects: { hunger: 20, stamina: 34 },
    useVerb: 'Eat',
  },
  bandage: {
    id: 'bandage',
    name: 'Bandage',
    short: 'Bandage',
    type: ItemType.CONSUMABLE,
    icon: '🩹',
    stack: 6,
    weight: 0.2,
    supply: 1,
    desc: 'Stops the bleeding. Does not fix what caused it.',
    effects: { health: 16, stopBleed: true },
    useVerb: 'Apply',
    useTime: 2.4,
  },
  painkillers: {
    id: 'painkillers',
    name: 'Painkillers',
    short: 'Pills',
    type: ItemType.CONSUMABLE,
    icon: '💊',
    stack: 4,
    weight: 0.1,
    supply: 1,
    desc: 'Takes the edge off. Blunts the shaking for a minute.',
    effects: { health: 8, stamina: 40, painkiller: 45 },
    useVerb: 'Take',
    useTime: 1.2,
  },
  medkit: {
    id: 'medkit',
    name: 'First Aid Kit',
    short: 'Med Kit',
    type: ItemType.CONSUMABLE,
    icon: '🧰',
    stack: 2,
    weight: 1.6,
    supply: 2,
    desc: 'Proper kit. Gauze, tape, antiseptic. Worth more than money now.',
    effects: { health: 58, stopBleed: true },
    useVerb: 'Use',
    useTime: 3.6,
  },
  glass_bottle: {
    id: 'glass_bottle',
    name: 'Empty Bottle',
    short: 'Bottle',
    type: ItemType.RESOURCE,
    icon: '🍾',
    stack: 6,
    weight: 0.4,
    desc: 'Somebody drank this before it all went wrong. Throws well. Breaks loud.',
    useVerb: 'Equip',
    weapon: 'bottle',
    throwable: true,
  },
  tin_can: {
    id: 'tin_can',
    name: 'Empty Can',
    short: 'Can',
    type: ItemType.RESOURCE,
    icon: '🥫',
    stack: 8,
    weight: 0.2,
    desc: 'Light, and it clatters for a long time. Worth more thrown than kept.',
    useVerb: 'Equip',
    weapon: 'can',
    throwable: true,
  },
  battery: {
    id: 'battery',
    name: 'Batteries',
    short: 'Battery',
    type: ItemType.RESOURCE,
    icon: '🔋',
    stack: 8,
    weight: 0.2,
    desc: 'Two AA. The difference between seeing and not seeing.',
    useVerb: 'Load',
    effects: { battery: 55 },
  },
  planks: {
    id: 'planks',
    name: 'Planks & Nails',
    short: 'Planks',
    type: ItemType.RESOURCE,
    icon: '🪵',
    stack: 4,
    weight: 3.2,
    desc: 'Enough to board one doorway. Heavy. Worth carrying anyway.',
  },
  ammo_38: {
    id: 'ammo_38',
    name: '.38 Rounds',
    short: 'Rounds',
    type: ItemType.AMMO,
    icon: '🔩',
    stack: 24,
    weight: 0.05,
    desc: 'Six of these could save you. Or bring the whole street down on you.',
  },

  // ── weapons ──────────────────────────────────────────────────────────
  kitchen_knife: {
    id: 'kitchen_knife',
    name: 'Kitchen Knife',
    short: 'Knife',
    type: ItemType.WEAPON,
    icon: '🔪',
    stack: 1,
    weight: 0.5,
    desc: 'Fast and quiet, but you have to get close. Too close.',
    weapon: 'knife',
  },
  crowbar: {
    id: 'crowbar',
    name: 'Crowbar',
    short: 'Crowbar',
    type: ItemType.WEAPON,
    icon: '⛏',
    stack: 1,
    weight: 2.4,
    desc: 'Honest weight. Good for doors, better for skulls.',
    weapon: 'crowbar',
  },
  baseball_bat: {
    id: 'baseball_bat',
    name: 'Baseball Bat',
    short: 'Bat',
    type: ItemType.WEAPON,
    icon: '🏏',
    stack: 1,
    weight: 1.9,
    desc: 'Aluminium, dented near the sweet spot. Someone already used it.',
    weapon: 'bat',
  },
  fire_axe: {
    id: 'fire_axe',
    name: 'Fire Axe',
    short: 'Axe',
    type: ItemType.WEAPON,
    icon: '🪓',
    stack: 1,
    weight: 3.6,
    desc: 'Slow. Heavy. Ends arguments in one swing if you land it.',
    weapon: 'axe',
  },
  machete: {
    id: 'machete',
    name: 'Machete',
    short: 'Machete',
    type: ItemType.WEAPON,
    icon: '🗡',
    stack: 1,
    weight: 1.2,
    desc: 'Garden-centre steel with a rolled edge. What it opens does not close.',
    weapon: 'machete',
  },
  sledgehammer: {
    id: 'sledgehammer',
    name: 'Sledgehammer',
    short: 'Sledge',
    type: ItemType.WEAPON,
    icon: '🔨',
    stack: 1,
    weight: 5.4,
    desc: 'Eight kilos on a metre of hickory. You get one swing. Make it count.',
    weapon: 'sledge',
  },
  molotov: {
    id: 'molotov',
    name: 'Molotov',
    short: 'Molotov',
    type: ItemType.RESOURCE,
    icon: '🔥',
    stack: 3,
    weight: 0.9,
    desc: 'Petrol and a rag. Burns whatever is standing in it, including you.',
    useVerb: 'Equip',
    weapon: 'molotov',
    throwable: true,
  },
  tools: {
    id: 'tools',
    name: 'Tool Roll',
    short: 'Tools',
    type: ItemType.TOOL,
    icon: '🛠',
    stack: 2,
    weight: 2.1,
    desc: 'A file, a whetstone, a roll of tape. Brings one weapon back a step.',
    useVerb: 'Repair',
    useTime: 3.0,
    repairs: true,
  },
  revolver: {
    id: 'revolver',
    name: 'Service Revolver',
    short: 'Revolver',
    type: ItemType.WEAPON,
    icon: '🔫',
    stack: 1,
    weight: 1.1,
    desc: 'Six chambers, and every shot is a dinner bell for the whole block.',
    weapon: 'revolver',
  },
  flashlight: {
    id: 'flashlight',
    name: 'Flashlight',
    short: 'Torch',
    type: ItemType.TOOL,
    icon: '🔦',
    stack: 1,
    weight: 0.6,
    desc: 'Lets you see. Lets them see you. [F] to toggle.',
  },
};

/**
 * Melee/ranged behaviour. Slower weapons hit much harder — no free wins.
 *
 * `damage` is tuned against the TTK table in `CFG.combat.ttk`: hits to put down
 * a fresh shambler with body shots. `durability` is hits at full condition
 * before the thing is scrap. `knockdown` marks the weapons heavy enough to put
 * an almost-dead target on the floor, and `trail` the ones whose arc is worth
 * drawing.
 */
export const WEAPONS = {
  fists: {
    id: 'fists',
    name: 'Fists',
    sub: 'bare hands',
    damage: 14,
    range: 1.5,
    arc: 62,
    windup: 0.12,
    active: 0.1,
    recover: 0.3,
    stamina: 8,
    knockback: 1.0,
    stagger: 0.18,
    noise: 4,
    swingSound: 'whoosh_light',
    hitSound: 'hit_soft',
    mesh: null,
    anim: 'punch',
    durability: null,        // nothing to break
  },
  knife: {
    id: 'knife',
    name: 'Kitchen Knife',
    sub: 'fast · short reach',
    damage: 17,
    range: 1.55,
    arc: 46,
    windup: 0.09,
    active: 0.09,
    recover: 0.25,
    stamina: 7,
    knockback: 0.7,
    stagger: 0.14,
    noise: 4,
    swingSound: 'whoosh_light',
    hitSound: 'hit_stab',
    mesh: 'knife',
    anim: 'stab',
    durability: 34,
  },
  crowbar: {
    id: 'crowbar',
    name: 'Crowbar',
    sub: 'balanced',
    damage: 28,
    range: 1.9,
    arc: 72,
    windup: 0.2,
    active: 0.12,
    recover: 0.42,
    stamina: 13,
    knockback: 2.1,
    stagger: 0.42,
    noise: 6,
    swingSound: 'whoosh',
    hitSound: 'hit_metal',
    mesh: 'crowbar',
    anim: 'light',
    durability: 90,
  },
  bat: {
    id: 'bat',
    name: 'Baseball Bat',
    sub: 'wide swing · knockdown',
    damage: 30,
    range: 2.15,
    arc: 96,
    windup: 0.26,
    active: 0.14,
    recover: 0.5,
    stamina: 15,
    knockback: 3.6,
    stagger: 0.6,
    noise: 7,
    swingSound: 'whoosh',
    hitSound: 'hit_blunt',
    mesh: 'bat',
    anim: 'light',
    durability: 62,
    knockdown: true,
    trail: 0.7,
  },
  machete: {
    id: 'machete',
    name: 'Machete',
    sub: 'fast · opens them up',
    damage: 26,
    range: 1.85,
    arc: 66,
    windup: 0.16,
    active: 0.1,
    recover: 0.3,
    stamina: 10,
    knockback: 1.5,
    stagger: 0.3,
    noise: 5,
    swingSound: 'whoosh',
    hitSound: 'hit_stab',
    mesh: 'machete',
    anim: 'light',
    durability: 46,
    bleed: 1,
    trail: 0.55,
  },
  axe: {
    id: 'axe',
    name: 'Fire Axe',
    sub: 'slow · devastating',
    damage: 58,
    range: 2.0,
    arc: 60,
    windup: 0.42,
    active: 0.14,
    recover: 0.72,
    stamina: 24,
    knockback: 2.8,
    stagger: 0.7,
    noise: 8,
    swingSound: 'whoosh_heavy',
    hitSound: 'hit_chop',
    mesh: 'axe',
    anim: 'heavy',
    durability: 40,
    trail: 0.9,
  },
  sledge: {
    id: 'sledge',
    name: 'Sledgehammer',
    sub: 'very slow · flattens a group',
    damage: 62,
    range: 2.1,
    arc: 112,
    windup: 0.62,
    active: 0.18,
    recover: 0.95,
    stamina: 30,
    knockback: 5.2,
    stagger: 1.0,
    noise: 9,
    swingSound: 'whoosh_heavy',
    hitSound: 'hit_blunt',
    mesh: 'sledge',
    anim: 'heavy',
    durability: 55,
    knockdown: true,
    trail: 1.0,
  },
  bottle: {
    id: 'bottle',
    name: 'Empty Bottle',
    sub: 'throw · pulls them to it',
    throwable: true,
    item: 'glass_bottle',
    damage: 4,
    range: 1.4,
    arc: 40,
    windup: 0.22,
    active: 0.06,
    recover: 0.4,
    stamina: 3,
    knockback: 0.2,
    stagger: 0.05,
    noise: 18,
    swingSound: 'whoosh_light',
    hitSound: 'hit_soft',
    mesh: null,
    anim: 'stab',
    shatters: true,
  },
  can: {
    id: 'can',
    name: 'Empty Can',
    sub: 'throw · quieter, reusable',
    throwable: true,
    item: 'tin_can',
    damage: 2,
    range: 1.4,
    arc: 40,
    windup: 0.2,
    active: 0.06,
    recover: 0.36,
    stamina: 2,
    knockback: 0.1,
    stagger: 0.02,
    noise: 13,
    swingSound: 'whoosh_light',
    hitSound: 'hit_soft',
    mesh: null,
    anim: 'stab',
    shatters: false,
  },
  molotov: {
    id: 'molotov',
    name: 'Molotov',
    sub: 'throw · burns everything',
    throwable: true,
    incendiary: true,
    item: 'molotov',
    damage: 6,
    range: 1.4,
    arc: 40,
    windup: 0.3,
    active: 0.06,
    recover: 0.55,
    stamina: 5,
    knockback: 0.3,
    stagger: 0.05,
    noise: 22,
    swingSound: 'whoosh',
    hitSound: 'hit_soft',
    mesh: 'molotov',
    anim: 'stab',
    shatters: true,
  },
  revolver: {
    id: 'revolver',
    name: 'Revolver',
    sub: '.38 · very loud',
    ranged: true,
    /**
     * Two to the chest or one to the head. A revolver that deleted anything it
     * touched made the noise cost irrelevant; at this number you still have to
     * decide whether the shot is worth the street hearing it.
     */
    damage: 50,
    range: 42,
    windup: 0.1,
    active: 0.05,
    recover: 0.62,
    stamina: 4,
    knockback: 3.0,
    stagger: 0.8,
    noise: 78,
    ammo: 'ammo_38',
    magazine: 6,
    mesh: 'revolver',
    anim: 'shoot',
  },
};

/**
 * Loot tables. `w` is relative weight; `null` id means "nothing here".
 * Emptiness is deliberate — the disappointment is part of the tension.
 */
export const LOOT_TABLES = {
  kitchen: [
    { w: 20, id: 'glass_bottle', n: [1, 2] },
    { w: 14, id: 'tin_can', n: [1, 2] },
    { w: 30, id: null },
    { w: 16, id: 'canned_food', n: [1, 2] },
    { w: 12, id: 'water_bottle', n: [1, 2] },
    { w: 8, id: 'energy_bar', n: [1, 2] },
    { w: 5, id: 'kitchen_knife' },
    { w: 4, id: 'battery' },
    { w: 3, id: 'soda', n: [1, 2] },
  ],
  bathroom: [
    { w: 26, id: null },
    { w: 18, id: 'bandage', n: [1, 2] },
    { w: 12, id: 'painkillers' },
    { w: 6, id: 'medkit' },
    { w: 8, id: 'water_bottle' },
  ],
  bedroom: [
    { w: 34, id: null },
    { w: 10, id: 'battery', n: [1, 2] },
    { w: 8, id: 'flashlight' },
    { w: 8, id: 'energy_bar' },
    { w: 6, id: 'bandage' },
    { w: 4, id: 'baseball_bat' },
  ],
  /**
   * The garage is where the session's new hardware lives. It is the most
   * dangerous kind of room to search — enclosed, one way out — so it is the
   * right place to put a sledgehammer and the tools that keep an axe alive.
   */
  garage: [
    { w: 12, id: 'glass_bottle', n: [1, 2] },
    { w: 24, id: null },
    { w: 13, id: 'planks' },
    { w: 11, id: 'crowbar' },
    { w: 9, id: 'tools' },
    { w: 8, id: 'battery', n: [1, 2] },
    { w: 6, id: 'fire_axe' },
    { w: 6, id: 'flashlight' },
    { w: 5, id: 'sledgehammer' },
    { w: 5, id: 'machete' },
    { w: 4, id: 'molotov', n: [1, 2] },
  ],
  store_shelf: [
    { w: 18, id: 'glass_bottle', n: [1, 3] },
    { w: 16, id: 'tin_can', n: [1, 3] },
    { w: 30, id: null },
    { w: 16, id: 'canned_food', n: [1, 3] },
    { w: 14, id: 'energy_bar', n: [1, 3] },
    { w: 10, id: 'soda', n: [1, 2] },
    { w: 6, id: 'battery', n: [1, 2] },
  ],
  store_cooler: [
    { w: 22, id: 'glass_bottle', n: [1, 3] },
    { w: 20, id: null },
    { w: 30, id: 'water_bottle', n: [1, 3] },
    { w: 18, id: 'soda', n: [1, 3] },
  ],
  register: [
    { w: 34, id: null },
    { w: 12, id: 'painkillers' },
    { w: 10, id: 'energy_bar', n: [1, 2] },
    { w: 8, id: 'battery' },
    { w: 5, id: 'ammo_38', n: [2, 4] },
  ],
  car_trunk: [
    { w: 12, id: 'glass_bottle' },
    { w: 26, id: null },
    { w: 12, id: 'water_bottle', n: [1, 2] },
    { w: 10, id: 'bandage' },
    { w: 10, id: 'planks' },
    { w: 8, id: 'crowbar' },
    { w: 8, id: 'battery' },
    { w: 6, id: 'tools' },
    { w: 5, id: 'energy_bar', n: [1, 2] },
    { w: 4, id: 'molotov' },
  ],
  medical: [
    { w: 12, id: null },
    { w: 24, id: 'bandage', n: [1, 3] },
    { w: 18, id: 'medkit' },
    { w: 14, id: 'painkillers', n: [1, 2] },
    { w: 10, id: 'water_bottle', n: [1, 2] },
  ],
  police: [
    { w: 16, id: null },
    { w: 20, id: 'ammo_38', n: [2, 5] },
    { w: 12, id: 'bandage', n: [1, 2] },
    { w: 10, id: 'flashlight' },
    { w: 8, id: 'medkit' },
  ],
  backpack: [
    { w: 12, id: 'tin_can', n: [1, 2] },
    { w: 14, id: null },
    { w: 20, id: 'water_bottle', n: [1, 2] },
    { w: 18, id: 'canned_food', n: [1, 2] },
    { w: 14, id: 'bandage', n: [1, 2] },
    { w: 10, id: 'energy_bar', n: [1, 2] },
    { w: 8, id: 'battery' },
  ],
  /**
   * Somebody camped here and did not stay. Whatever they had worked out about
   * surviving the first night is lying where they left it.
   */
  camp: [
    { w: 16, id: 'tin_can', n: [1, 3] },
    { w: 12, id: 'glass_bottle', n: [1, 2] },
    { w: 20, id: null },
    { w: 17, id: 'canned_food', n: [1, 2] },
    { w: 15, id: 'water_bottle', n: [1, 2] },
    { w: 10, id: 'painkillers' },
    { w: 8, id: 'planks' },
    { w: 7, id: 'molotov', n: [1, 2] },
    { w: 6, id: 'energy_bar' },
    { w: 5, id: 'machete' },
    { w: 4, id: 'tools' },
  ],
};

/** Roll a table into a list of {id, count}. */
export function rollLoot(tableId, rng, luck = 1) {
  const table = LOOT_TABLES[tableId];
  if (!table) return [];
  // Luck biases away from the "nothing" entry.
  const weighted = table.map((e) => ({ ...e, w: e.id === null ? e.w / luck : e.w * luck }));
  const pick = rng.weighted(weighted);
  if (!pick || !pick.id) return [];
  const n = pick.n ? rng.int(pick.n[0], pick.n[1]) : 1;
  return [{ id: pick.id, count: n }];
}
